//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PISAEntity : DbContext
    {
        public PISAEntity()
            : base("name=PISAEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblBook> TblBook { get; set; }
        public virtual DbSet<TblHobby> TblHobby { get; set; }
        public virtual DbSet<TblMagazine> TblMagazine { get; set; }
        public virtual DbSet<TblMovie> TblMovie { get; set; }
        public virtual DbSet<TblMusic> TblMusic { get; set; }
        public virtual DbSet<TblPerson> TblPerson { get; set; }
    }
}
