//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHobby
    {
        public int HobbyId { get; set; }
        public string HobbyName { get; set; }
        public string HobbyType { get; set; }
        public Nullable<decimal> HobbyPrice { get; set; }
        public Nullable<int> HobbyStock { get; set; }
        public byte[] HobbyImage { get; set; }
        public Nullable<int> HobbyPoint { get; set; }
        public Nullable<int> HobbyAmount { get; set; }
    }
}
