//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMovie
    {
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public string MovieDirector { get; set; }
        public Nullable<int> MovieYear { get; set; }
        public string MovieGenre { get; set; }
        public Nullable<double> MovieRuntime { get; set; }
        public Nullable<decimal> MoviePrice { get; set; }
        public Nullable<int> MovieStock { get; set; }
        public byte[] MovieImage { get; set; }
        public Nullable<int> MoviePoint { get; set; }
        public Nullable<int> MovieAmount { get; set; }
    }
}
