//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMusic
    {
        public int MusicId { get; set; }
        public string MusicName { get; set; }
        public string MusicSinger { get; set; }
        public string MusicType { get; set; }
        public Nullable<decimal> MusicPrice { get; set; }
        public Nullable<int> MusicStock { get; set; }
        public byte[] MusicImage { get; set; }
        public Nullable<int> MusicPoint { get; set; }
        public Nullable<int> MusicAmount { get; set; }
    }
}
