//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMagazine
    {
        public int MagazineId { get; set; }
        public string MagazineName { get; set; }
        public string MagazineType { get; set; }
        public Nullable<decimal> MagazinePrice { get; set; }
        public Nullable<int> MagazineStock { get; set; }
        public byte[] MagazineImage { get; set; }
        public Nullable<int> MagazinePoint { get; set; }
        public Nullable<int> MagazineAmount { get; set; }
    }
}
