//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPerson
    {
        public int PersonId { get; set; }
        public string PersonName { get; set; }
        public string PersonSurname { get; set; }
        public string PersonUsername { get; set; }
        public string PersonPassword { get; set; }
        public string PersonAddress { get; set; }
        public string PersonMail { get; set; }
        public string PersonType { get; set; }
        public Nullable<decimal> PersonCardNumber { get; set; }
        public Nullable<int> PersonTotalPoint { get; set; }
    }
}
